### PR TITLE
Add MRI 2.5 to the known Ruby versions.

### PR DESCRIPTION
**Pull request by pat**
As discussed in #109, here are the changes required for MRI 2.5 support.

### CODE REVIEW

**Comment by pat** [comment]
Also: if it's useful, I can submit another PR that extends the tested Ruby versions to cover the latest 2.x releases (rather than just 2.3) - though it's a simple enough change for a maintainer to do directly :)

**Comment by apeeters** [comment]
Would be nice to have this included soon since it is required for the Ubuntu Bionic release next Monday. Also an update of the dependencies of the deb package is needed.

**Comment by analytically** [comment]
"Current running Ruby version for root is 2.5.1, but Ruby version 2.x needs to be installed." when running on Ubuntu 18.04

**Comment by carlnordenfelt** [comment]
I raised this issue before I saw this PR: https://github.com/aws/aws-codedeploy-agent/issues/158

**Comment by pat** [comment]
This is not a recommendation - I'm not yet using this seriously in production - but how I've gone about installing things:

As noted by others here, the underlying package has a dependency on ruby2.0/ruby2.1/ruby2.2/ruby2.3. To work around this, I've got another branch that [installs the package while ignoring the Ruby requirements](https://github.com/pat/aws-codedeploy-agent/commit/aba358d31615aca327cb22a4314f321090dc0ac2) (I've already compiled Ruby manually), and I use that instead:

```
wget "https://raw.githubusercontent.com/pat/aws-codedeploy-agent/mri2.5.0-no-dep/bin/install"

chmod +x ./install
sudo ./install auto
```

Use with extreme caution, and test thoroughly :)

**Comment by f-breidenstein** [comment]
Hi @rohkat-aws, any updates on adding Ruby 2.5 support? 
I don't want to sound rude or create any preasure but this PR is now half a year old and with the missing 2.5 support, many distros (incl. current Ubuntu LTS) are not able to install the CDA without any tinkering on the system.

I sadly have no Ruby experience, but let me now if I can help with anything :)

Best regards and thanks for your work!

**Pull request merged**
