### PR TITLE
Use ruby greater than 2.6

### PR DESCRIPTION
**Pull request by vrr-21**
*Issue #, if available:*

*Description of changes:*
Upgrading the acceptable ruby version to 2.6.0 or greater as Ruby versions below 2.5 are now [end-of-life](https://www.ruby-lang.org/en/downloads/branches/).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by vrr-21** [comment]
Removing Ruby backwards compatibility might be a breaking change for many customers. Hence we'd like to exercise caution around that.

**Comment by ajanata** [comment]
Adding the requirement for `2.3.8` in 2f74f7d actively broke us; we don't have that version installed and for whatever reason it refuses to install on our boxes and also prevents us from upgrading it. Can you consider removing `.ruby-version` altogether?

**Comment by vrr-21** [comment]
This PR is closed, and will not be monitored.

Can you open an issue with this request? We'd be happy to take a look at it and explore any possibilities.

**Comment by ajanata** [comment]
And I'm saying it was closed for an invalid reason. There was no forced Ruby version until 2 months ago, at which time it was forced to be version that's been out of support for over 3 years. Either revert that change or re-open and merge this.

**Comment by philstrong** [comment]
We haven't heard from anyone else that this is an issue. What version of Ruby are you trying to use? What OS platform?

**Pull request closed without merging**
