### PR TITLE
Add support to Ruby version 2.6

### PR DESCRIPTION
**Pull request by mujz**
*Issue #, if available:* #214 

*Description of changes:* Add support for Ruby 2.6 to the install script

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

I already tested this and it seems to work just fine.

### CODE REVIEW

**Comment by mujz** [comment]
Ping. Can an admin please look at this?
@rohkat-aws @pmzara @annamataws

**Comment by inductor** [comment]
https://github.com/aws/aws-codedeploy-agent/pull/196 This as well :(

**Comment by mujz** [comment]
Seems like nobody is maintaining this repo anymore :(

**Comment by rohkat-aws** [comment]
the ruby 2.6 will have to be tested internally before we release it as a supported ruby version @mujz

**Comment by mujz** [comment]
Great to hear from you @rohkat-aws. Thanks for your input!
That makes sense. Would you be able to provide any input on how long it might take for the internal testing? I understand that it's hard to give time estimates, so I won't hold you to it. Just knowing whether this is something that somebody is working on or not is all I'm looking to know here.

**Comment by mujz** [comment]
@rohkat-aws any update on this? Last I heard from you was about a month ago.

**Pull request closed without merging**
