### PR TITLE
Ignore non-empty directories when cleanup

### PR DESCRIPTION
**Pull request by spilist**
This closes aws#185.

### Description of changes
When installing ruby in `ubuntu 18.04`, ruby version `2.5.x` is installed by default.

Before ruby `2.5`(i.e., `2.4.3`), `FileUtils.rmdir` [silently fails when the target directory is not empty](https://ruby-doc.org/stdlib-2.4.3/libdoc/fileutils/rdoc/FileUtils.html#method-c-rmdir), so the non-empty directories in cleanup file are not removed on deployment, and the deployment succeeds. 

But the implementation of `FileUtils.rmdir` is [changed in ruby `2.5`](https://ruby-doc.org/stdlib-2.5.0/libdoc/fileutils/rdoc/FileUtils.html#method-c-rmdir) so that it doesn’t rescue `Errno::ENOTEMPTY` any more, which generates failures on deployment.

This PR adds a rescue from `Errno::ENOTEMPTY`, thus non-empty directories in cleanup file are not removed for ruby 2.5 and forward, and the deployment does not fail.

---

Note: There are two other exceptions(`Errno::EEXIST`, `Errno::ENOENT`) that can occur in `FileUtils.rmdir` and have been rescued before ruby `2.5`. We don't rescue them here because:
- `Errno::EEXIST` - [File exists](http://www-numi.fnal.gov/offline_software/srt_public_context/WebDocs/Errors/unix_system_errors.html): it doesn't occur in our use case. (Frankly I have no idea why this rescue is needed from the first time)
- `Errno::ENOENT` - [No such file or directory](http://www-numi.fnal.gov/offline_software/srt_public_context/WebDocs/Errors/unix_system_errors.html): it doesn't occur since we first check `File.exist?(@file_path)` before `FileUtils.rmdir(@file_path)` is executed. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ceejayoz** [comment]
Just wanted to chime in that we're affected by this on Ubuntu 18.04 ourselves.

**Comment by dlo** [comment]
Could someone on the AWS team please prioritize this for a merge? This is affecting our FE deployments.

**Comment by lweb20** [comment]
Please merge this PR

**Comment by bschaefer99** [comment]
Can we get a little mergy merge here?

**Comment by stevethomas** [comment]
I'm definitely impacted by this and waiting for the merge. 

What i'm not understanding, is if my appspec.yml has a `destination` of `/home/ubuntu/codinglabs/new`, why does the cleanup log have a first entry of `/home/ubuntu/codinglabs` (followed by expected entries for `/home/ubuntu/codinglabs/new/...`?

The Code Deploy agent wants to delete the non-empty `/home/ubuntu/codinglabs` and is failing at this point after the first deploy, even though it is outside of the desired destination.

Creating `/home/ubuntu/codinglabs` prior to deployment is not helping.

**Comment by danielforer** [comment]
I have the same issue on Ubuntu 18.04. Can this be merged? If not, can we get a reason why?

**Comment by andres-b6realestateadvisors** [comment]
Can this please be merged?

**Comment by alinalexandru** [comment]
We are blocked by this bug in our Ubuntu 18 stack.
Can we just please merge?

**Comment by bschaefer99** [comment]
@rohkat-aws Can you help us get this merged? It would simplify things for many of us.

**Comment by rmalca** [comment]
solution to all problems: azure :v:

**Comment by rohkat-aws** [comment]
@bschaefer99 we are right now working on some other fixes , which were priortized , having said that this will be merged , we really dont want to push out a lot of changes together.

**Comment by bjclark13** [comment]
Yo yo let's git it

**Comment by haytham-salhi** [comment]
Yeah this issue appeared once we upgrade to ubuntu 18. Please do merge this issue!

**Comment by shamimmirzai** [comment]
Also having this problem since upgrading to Ubuntu 18.  Please merge this.  Thanks

**Comment by grejdi** [comment]
Here is some quick instructions for applying this PR's changes to your deployment in case it makes it easier for anyone:
```sh
# apply this PR's changes
sudo vim /opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/install_instruction.rb
# restart the codedeploy service
sudo service codedeploy-agent restart
```
Unfortunate, that this is taking this long, as without it, CodeDeploy is useless on Ubuntu 18.04.

**Comment by woodhull** [comment]
Since AWS seems to have abandoned maintenance for their CodeDeploy product what are others considering migrating to? I'd pay to use something that behaved similarly if it was maintained... Is it possible to recreate the same workflow and nice web UI using something like ansible? Other ideas for alternatives to switch to?

@rohkat-aws Perhaps you might have advice for other tools we should consider researching as an alternative to CodeDeploy given Ubuntu 18.04 support has been broken for 2+ years at this point?

**Comment by annamataws** [comment]
Hi all,

I apologize for the long turn-around time for pull requests. We are working on fixing our agent release process so we can incorporate changes and pull requests faster. We apologize for the delay.

**Comment by fleaz** [comment]
Yeah, something is happening in this repository. Thank you @Helen1987  🎉

**Comment by pajel** [comment]
So this has been merged but not included in any Codedeploy release, right?
@Helen1987 would you please know when a new version of Codedeploy including this fix will be released? Thank you.

**Comment by woodhull** [comment]
@pajel based on past experience "maybe in a few years". 

If anyone here has a premium support relationship with AWS it may be helpful to reach out through that avenue to bring attention to what seems like easily solvable problems with CodeDeploy: all it needs is some process to accept and deploy the bug fixes the community has submitted.

**Comment by Helen1987** [comment]
@pajel, we are actively working on a new release (and new release process). This change will be included in a new release.

**Comment by reecejmarkowsky** [comment]
is it possible to expedite the new release? thanks!

**Pull request merged**
